### ISSUE TITLE
PhraseApp addon

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/rails-templates#202]
### Why

We are using PhraseApp for localization so should we add PhraseApp to our template 

### Example

1/ Phrase app configuration

```
phraseapp:
  project_id: bdea2635d5497b473439bf269915c85e
  file_format: yml
  push:
    sources:
    - file: ./config/locales/<tag>.<locale_name>.yml
      params:
        skip_upload_tags: true
  pull:
    targets:
    - file: ./config/locales/<tag>.<locale_name>.yml
      params:
        include_empty_translations: true
        tags: tag_name
    ...
```
