### ISSUE TITLE
Missing Redis configuration in Docker file.

### ISSUE THREAD

**Issue by Yutna** [nimblehq/rails-templates#67]
I can NOT run the `Procfile.dev` to start the application server because it missing the Redis configuration in the docker file.

please add this to the docker file.

```yml
redis:
    image: redis:4.0.9
    container_name: <app-name>_redis
    ports:
      - "6379:6379"
```
